[package]
name = "framework"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
math = { path = "../math" }
engine = { path = "../engine" }
log = { workspace = true }
winit = "0.30.13"
image = { version = "0.25", default-features = false, features = ["png"] }
fontdue = "0.9.4"
