name: devlog

on:
  push:
    paths:
      - devlog/**
      - .github/workflows/devlog.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install mdbook
        run: cargo install mdbook

      - name: Test
        run: just devlog/build
